### PR TITLE
Add missing Provider.tf

### PR DESCRIPTION
**Pull request by brtkwr**

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Nice. I know little of tf, so will let @johnstudarus comment. thanks!

**Comment by johnstudarus** [comment]
The Provider is implicit when you use a Packet Device and set the token and
project via an environment variable. However, you would need it if you use
a different variable name.

It won't hurt anything to explicitly add in the Provider and set the
variable. Let me test run the code and then I'll merge.

**Comment by brtkwr** [comment]
Hmm I was being asked to enter packet.auth_token without the Provider.tf and noticed that osa-workshop contains this file which is missing here and the problem went away.

**Comment by johnstudarus** [comment]
Ah - I had an environment variable set with auth_token and that's why my environment worked OK without the explicit Provider. I've validated on a pristine environment and will merge in.

**Pull request merged**
